/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MDXTablePlugin
});
module.exports = __toCommonJS(main_exports);
var import_state2 = require("@codemirror/state");
var import_obsidian = require("obsidian");

// src/core/parser.ts
function splitCells(rowText) {
  let txt = rowText.trim();
  if (txt.startsWith("|"))
    txt = txt.slice(1);
  if (txt.endsWith("|"))
    txt = txt.slice(0, -1);
  const cells = [];
  let currentCell = "";
  for (let i = 0; i < txt.length; i++) {
    const char = txt[i];
    if (char === "\\" && i + 1 < txt.length && txt[i + 1] === "|") {
      currentCell += "|";
      i++;
    } else if (char === "|") {
      cells.push(currentCell.trim());
      currentCell = "";
    } else {
      currentCell += char;
    }
  }
  cells.push(currentCell.trim());
  return cells;
}
function parseSeparatorRow(rowText) {
  const cells = splitCells(rowText);
  const colsMeta = [];
  const sepRegex = /^\s*(:?)-+(\[[^\]]+\])?(:?)\s*$/;
  for (const cell of cells) {
    const match = cell.match(sepRegex);
    if (!match) {
      return null;
    }
    const hasLeftColon = !!match[1];
    const widthRaw = match[2];
    const hasRightColon = !!match[3];
    let align = "default";
    if (hasLeftColon && hasRightColon) {
      align = "center";
    } else if (hasRightColon) {
      align = "right";
    } else if (hasLeftColon) {
      align = "left";
    }
    let width;
    if (widthRaw) {
      width = widthRaw.slice(1, -1).trim();
    }
    colsMeta.push({ align, width });
  }
  return colsMeta;
}
function parseTableMeta(commentText) {
  const match = commentText.match(/<!--\s*\{\.md-xtable\s+([^}]+)\}\s*-->/);
  if (!match)
    return null;
  const attrStr = match[1];
  const attributes = {};
  const classes = [];
  let id;
  let width;
  let calc;
  const classRegex = /\.([^\s#=]+)/g;
  const idRegex = /#([^\s#=]+)/g;
  const kvRegex = /([a-zA-Z0-9_-]+)\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s]+))/g;
  let m;
  while ((m = classRegex.exec(attrStr)) !== null) {
    classes.push(m[1]);
  }
  classRegex.lastIndex = 0;
  while ((m = idRegex.exec(attrStr)) !== null) {
    id = m[1];
  }
  idRegex.lastIndex = 0;
  while ((m = kvRegex.exec(attrStr)) !== null) {
    const key = m[1];
    const val = m[2] || m[3] || m[4];
    if (key === "id") {
      id = val;
    } else if (key === "class") {
      classes.push(val);
    } else if (key === "width") {
      width = val;
    } else if (key === "calc") {
      if (val === "auto" || val === "manual") {
        calc = val;
      }
    } else {
      attributes[key] = val;
    }
  }
  kvRegex.lastIndex = 0;
  return {
    id,
    className: classes.length > 0 ? classes.join(" ") : void 0,
    width,
    calc,
    attributes
  };
}
function parseMarkdownTable(markdown) {
  const lines = markdown.split(/\r?\n/).map((l) => l.trim());
  if (lines.length < 2)
    return null;
  let separatorRowIndex = -1;
  let colsMeta = null;
  for (let i = 1; i < Math.min(lines.length, 5); i++) {
    const meta = parseSeparatorRow(lines[i]);
    if (meta) {
      colsMeta = meta;
      separatorRowIndex = i;
      break;
    }
  }
  if (!colsMeta || separatorRowIndex === -1) {
    return null;
  }
  const headerLine = lines[separatorRowIndex - 1];
  const headerCells = splitCells(headerLine);
  const rawRows = [headerCells];
  let tableEndIndex = separatorRowIndex + 1;
  for (; tableEndIndex < lines.length; tableEndIndex++) {
    const line = lines[tableEndIndex];
    if (line === "" || !line.includes("|")) {
      break;
    }
    rawRows.push(splitCells(line));
  }
  let tableMeta = { attributes: {} };
  for (let i = tableEndIndex; i < lines.length; i++) {
    const line = lines[i];
    if (line === "")
      continue;
    const meta = parseTableMeta(line);
    if (meta) {
      tableMeta = meta;
      break;
    }
    if (!line.startsWith("<!--"))
      break;
  }
  const R = rawRows.length;
  const C = colsMeta.length;
  const rows = [];
  for (let r = 0; r < R; r++) {
    const rowCells = [];
    const rawCells = rawRows[r];
    for (let c = 0; c < C; c++) {
      const rawText = rawCells[c] || "";
      const isFormula = rawText.trim().startsWith(":=");
      const formula = isFormula ? rawText.trim().slice(2).trim() : void 0;
      rowCells.push({
        row: r,
        col: c,
        raw: rawText,
        value: isFormula ? "" : rawText,
        isFormula,
        formula,
        rowspan: 1,
        colspan: 1,
        isMerged: false
      });
    }
    rows.push(rowCells);
  }
  resolveCellMerges(rows, R, C);
  return {
    rows,
    colsMeta,
    tableMeta
  };
}
function resolveCellMerges(rows, R, C) {
  const rowsCovered = {};
  const colsCovered = {};
  for (let r = 0; r < R; r++) {
    for (let c = 0; c < C; c++) {
      const key = `${r},${c}`;
      rowsCovered[key] = /* @__PURE__ */ new Set([r]);
      colsCovered[key] = /* @__PURE__ */ new Set([c]);
    }
  }
  function getMaster(r, c) {
    const cell = rows[r][c];
    if (cell.isMerged && cell.mergedInto) {
      return getMaster(cell.mergedInto.row, cell.mergedInto.col);
    }
    return { row: r, col: c };
  }
  for (let r = 0; r < R; r++) {
    for (let c = 1; c < C; c++) {
      const cell = rows[r][c];
      if (cell.raw.trim() === "<") {
        const masterCoord = getMaster(r, c - 1);
        cell.isMerged = true;
        cell.mergedInto = masterCoord;
        const mKey = `${masterCoord.row},${masterCoord.col}`;
        const currKey = `${r},${c}`;
        rowsCovered[currKey].forEach((row) => rowsCovered[mKey].add(row));
        colsCovered[currKey].forEach((col) => colsCovered[mKey].add(col));
      }
    }
  }
  for (let c = 0; c < C; c++) {
    for (let r = 1; r < R; r++) {
      const cell = rows[r][c];
      if (cell.raw.trim() === "^^") {
        const masterCoord = getMaster(r - 1, c);
        cell.isMerged = true;
        cell.mergedInto = masterCoord;
        const mKey = `${masterCoord.row},${masterCoord.col}`;
        const currKey = `${r},${c}`;
        rowsCovered[currKey].forEach((row) => rowsCovered[mKey].add(row));
        colsCovered[currKey].forEach((col) => colsCovered[mKey].add(col));
      }
    }
  }
  for (let r = 0; r < R; r++) {
    for (let c = 0; c < C; c++) {
      const cell = rows[r][c];
      if (!cell.isMerged) {
        const key = `${r},${c}`;
        cell.rowspan = rowsCovered[key].size;
        cell.colspan = colsCovered[key].size;
      }
    }
  }
}

// src/core/evaluator.ts
function colLetterToNum(letter) {
  let num = 0;
  const upper = letter.toUpperCase();
  for (let i = 0; i < upper.length; i++) {
    num = num * 26 + (upper.charCodeAt(i) - 64);
  }
  return num - 1;
}
function numToColLetter(num) {
  let temp = num;
  let letter = "";
  while (temp >= 0) {
    letter = String.fromCharCode(temp % 26 + 65) + letter;
    temp = Math.floor(temp / 26) - 1;
  }
  return letter;
}
function parseCoordinate(coord) {
  const match = coord.match(/^([A-Z]+)([0-9]+)$/i);
  if (!match) {
    throw new Error(`Invalid coordinate: ${coord}`);
  }
  const colLetter = match[1];
  const rowNum = parseInt(match[2], 10);
  return {
    col: colLetterToNum(colLetter),
    row: rowNum - 1
  };
}
function preprocessRelativeReferences(formula, r, c) {
  const colLetter = numToColLetter(c);
  let upReplacement = "0";
  if (r >= 2) {
    upReplacement = `${colLetter}2:${colLetter}${r}`;
  } else if (r === 1) {
    upReplacement = "0";
  }
  let leftReplacement = "0";
  if (c >= 1) {
    const prevColLetter = numToColLetter(c - 1);
    const formulaRow = r + 1;
    leftReplacement = `A${formulaRow}:${prevColLetter}${formulaRow}`;
  }
  let processed = formula.replace(/\[UP\]/gi, upReplacement);
  processed = processed.replace(/\[LEFT\]/gi, leftReplacement);
  return processed;
}
function tokenize(expr) {
  const cleanExpr = expr.replace(/\s+/g, "");
  const tokens = [];
  let i = 0;
  while (i < cleanExpr.length) {
    const char = cleanExpr[i];
    if (char === "(") {
      tokens.push({ type: "LPAREN", value: "(" });
      i++;
      continue;
    }
    if (char === ")") {
      tokens.push({ type: "RPAREN", value: ")" });
      i++;
      continue;
    }
    if (char === ",") {
      tokens.push({ type: "COMMA", value: "," });
      i++;
      continue;
    }
    if (["+", "-", "*", "/"].includes(char)) {
      tokens.push({ type: "OPERATOR", value: char });
      i++;
      continue;
    }
    if (/[0-9]/.test(char) || char === "." && i + 1 < cleanExpr.length && /[0-9]/.test(cleanExpr[i + 1])) {
      let numStr = "";
      while (i < cleanExpr.length && /[0-9.]/.test(cleanExpr[i])) {
        numStr += cleanExpr[i];
        i++;
      }
      tokens.push({ type: "NUMBER", value: numStr });
      continue;
    }
    if (/[a-zA-Z_]/.test(char)) {
      let idStr = "";
      while (i < cleanExpr.length && /[a-zA-Z0-9_:]/.test(cleanExpr[i])) {
        idStr += cleanExpr[i];
        i++;
      }
      if (/^[a-zA-Z]+[0-9]+:[a-zA-Z]+[0-9]+$/.test(idStr)) {
        tokens.push({ type: "RANGE", value: idStr.toUpperCase() });
      } else if (/^[a-zA-Z]+[0-9]+$/.test(idStr)) {
        tokens.push({ type: "CELL", value: idStr.toUpperCase() });
      } else {
        tokens.push({ type: "IDENTIFIER", value: idStr });
      }
      continue;
    }
    throw new Error(`Unexpected character at position ${i}: ${char}`);
  }
  tokens.push({ type: "EOF", value: "" });
  return tokens;
}
function safeParseFloat(val) {
  if (!val)
    return 0;
  const clean = val.replace(/,/g, "").replace(/[^\d.-]/g, "").trim();
  const num = parseFloat(clean);
  return isNaN(num) ? 0 : num;
}
function evaluateGrid(grid, context = {}) {
  const rows = grid.rows;
  const R = rows.length;
  const C = R > 0 ? rows[0].length : 0;
  const formulaTokens = {};
  const dependencies = {};
  for (let r = 0; r < R; r++) {
    for (let c = 0; c < C; c++) {
      const cell = rows[r][c];
      if (cell.isFormula && cell.formula) {
        const key = `${r},${c}`;
        const preprocessed = preprocessRelativeReferences(cell.formula, r, c);
        try {
          const tokens = tokenize(preprocessed);
          formulaTokens[key] = tokens;
          const deps = [];
          for (const token of tokens) {
            if (token.type === "CELL") {
              const coord = parseCoordinate(token.value);
              deps.push(`${coord.row},${coord.col}`);
            } else if (token.type === "RANGE") {
              const parts = token.value.split(":");
              const start = parseCoordinate(parts[0]);
              const end = parseCoordinate(parts[1]);
              const rStart = Math.min(start.row, end.row);
              const rEnd = Math.max(start.row, end.row);
              const cStart = Math.min(start.col, end.col);
              const cEnd = Math.max(start.col, end.col);
              for (let dr = rStart; dr <= rEnd; dr++) {
                for (let dc = cStart; dc <= cEnd; dc++) {
                  deps.push(`${dr},${dc}`);
                }
              }
            }
          }
          dependencies[key] = deps;
        } catch (e) {
          cell.value = `#ERROR!`;
        }
      }
    }
  }
  const visited = {};
  const evalOrder = [];
  const cycles = /* @__PURE__ */ new Set();
  const stack = [];
  function dfs(key) {
    if (visited[key] === "visiting") {
      const index = stack.indexOf(key);
      if (index !== -1) {
        for (let i = index; i < stack.length; i++) {
          cycles.add(stack[i]);
        }
      }
      cycles.add(key);
      return;
    }
    if (visited[key] === "visited")
      return;
    visited[key] = "visiting";
    stack.push(key);
    const deps = dependencies[key] || [];
    for (const dep of deps) {
      if (dependencies[dep]) {
        dfs(dep);
      }
    }
    stack.pop();
    visited[key] = "visited";
    evalOrder.push(key);
  }
  for (const key of Object.keys(dependencies)) {
    if (!visited[key]) {
      dfs(key);
    }
  }
  for (const key of cycles) {
    const [r, c] = key.split(",").map(Number);
    rows[r][c].value = "#REF!";
  }
  for (const key of evalOrder) {
    if (cycles.has(key))
      continue;
    const [r, c] = key.split(",").map(Number);
    const cell = rows[r][c];
    const tokens = formulaTokens[key];
    if (!tokens)
      continue;
    try {
      let tokenIndex = 0;
      const peek = () => tokens[tokenIndex];
      const consume = (expectedType) => {
        const t = tokens[tokenIndex];
        if (expectedType && t.type !== expectedType) {
          throw new Error(`Expected ${expectedType}, got ${t.type}`);
        }
        tokenIndex++;
        return t;
      };
      const parseExpression = () => {
        let val = parseTerm();
        while (peek().type === "OPERATOR" && (peek().value === "+" || peek().value === "-")) {
          const op = consume().value;
          const right = parseTerm();
          if (op === "+")
            val += right;
          else
            val -= right;
        }
        return val;
      };
      const parseTerm = () => {
        let val = parseFactor();
        while (peek().type === "OPERATOR" && (peek().value === "*" || peek().value === "/")) {
          const op = consume().value;
          const right = parseFactor();
          if (op === "*")
            val *= right;
          else {
            if (right === 0)
              throw new Error("Division by zero");
            val /= right;
          }
        }
        return val;
      };
      const parseFactor = () => {
        const t = peek();
        if (t.type === "NUMBER") {
          consume();
          return parseFloat(t.value);
        }
        if (t.type === "OPERATOR" && (t.value === "+" || t.value === "-")) {
          const op = consume().value;
          const val = parseFactor();
          return op === "-" ? -val : val;
        }
        if (t.type === "LPAREN") {
          consume();
          const val = parseExpression();
          consume("RPAREN");
          return val;
        }
        if (t.type === "CELL") {
          consume();
          const coord = parseCoordinate(t.value);
          if (coord.row < 0 || coord.row >= R || coord.col < 0 || coord.col >= C) {
            return 0;
          }
          return safeParseFloat(rows[coord.row][coord.col].value);
        }
        if (t.type === "IDENTIFIER") {
          const name = consume().value;
          if (peek().type === "LPAREN") {
            consume("LPAREN");
            const args = [];
            if (peek().type !== "RPAREN") {
              args.push(parseArgument());
              while (peek().type === "COMMA") {
                consume("COMMA");
                args.push(parseArgument());
              }
            }
            consume("RPAREN");
            return evalFunction(name, args);
          } else {
            const keyLower = name.toLowerCase();
            const ctxKey = Object.keys(context).find(
              (k) => k.toLowerCase() === keyLower
            );
            if (ctxKey !== void 0) {
              return context[ctxKey];
            }
            throw new Error(`Undefined variable: ${name}`);
          }
        }
        throw new Error(`Unexpected token: ${t.type} (${t.value})`);
      };
      const parseArgument = () => {
        if (peek().type === "RANGE") {
          const rToken = consume();
          const parts = rToken.value.split(":");
          const start = parseCoordinate(parts[0]);
          const end = parseCoordinate(parts[1]);
          const rStart = Math.min(start.row, end.row);
          const rEnd = Math.max(start.row, end.row);
          const cStart = Math.min(start.col, end.col);
          const cEnd = Math.max(start.col, end.col);
          const values = [];
          for (let dr = rStart; dr <= rEnd; dr++) {
            for (let dc = cStart; dc <= cEnd; dc++) {
              if (dr >= 0 && dr < R && dc >= 0 && dc < C) {
                values.push(safeParseFloat(rows[dr][dc].value));
              }
            }
          }
          return values;
        }
        return parseExpression();
      };
      const evalFunction = (name, args) => {
        const flat = [];
        for (const arg of args) {
          if (Array.isArray(arg)) {
            flat.push(...arg);
          } else {
            flat.push(arg);
          }
        }
        const upperName = name.toUpperCase();
        if (upperName === "SUM") {
          return flat.reduce((s, v) => s + v, 0);
        }
        if (upperName === "AVERAGE") {
          if (flat.length === 0)
            return 0;
          return flat.reduce((s, v) => s + v, 0) / flat.length;
        }
        if (upperName === "COUNT") {
          return flat.length;
        }
        if (upperName === "PRODUCT") {
          if (flat.length === 0)
            return 0;
          return flat.reduce((p, v) => p * v, 1);
        }
        throw new Error(`Unknown function: ${name}`);
      };
      const result = parseExpression();
      consume("EOF");
      cell.value = Number.isInteger(result) ? result.toString() : result.toFixed(2);
    } catch (e) {
      cell.value = `#VALUE!`;
    }
  }
}

// src/core/renderer.ts
function renderTable(grid, doc = document) {
  const table = doc.createElement("table");
  if (grid.tableMeta.id) {
    table.id = grid.tableMeta.id;
  }
  table.className = "md-xtable";
  if (grid.tableMeta.className) {
    table.className += " " + grid.tableMeta.className;
  }
  if (grid.tableMeta.width) {
    table.style.width = grid.tableMeta.width;
  }
  for (const [key, val] of Object.entries(grid.tableMeta.attributes)) {
    table.setAttribute(key, val);
  }
  const rows = grid.rows;
  if (rows.length === 0)
    return table;
  const thead = doc.createElement("thead");
  const headRow = doc.createElement("tr");
  const headCells = rows[0];
  for (let c = 0; c < headCells.length; c++) {
    const cell = headCells[c];
    if (cell.isMerged)
      continue;
    const th = doc.createElement("th");
    th.textContent = cell.value;
    if (cell.colspan > 1)
      th.colSpan = cell.colspan;
    if (cell.rowspan > 1)
      th.rowSpan = cell.rowspan;
    applyColumnStyles(th, c, grid.colsMeta);
    headRow.appendChild(th);
  }
  thead.appendChild(headRow);
  table.appendChild(thead);
  if (rows.length > 1) {
    const tbody = doc.createElement("tbody");
    for (let r = 1; r < rows.length; r++) {
      const tr = doc.createElement("tr");
      const bodyCells = rows[r];
      for (let c = 0; c < bodyCells.length; c++) {
        const cell = bodyCells[c];
        if (cell.isMerged)
          continue;
        const td = doc.createElement("td");
        if (cell.isFormula) {
          td.classList.add("md-xtable-formula");
          td.setAttribute("data-formula", cell.formula || "");
        }
        td.textContent = cell.value;
        if (cell.colspan > 1)
          td.colSpan = cell.colspan;
        if (cell.rowspan > 1)
          td.rowSpan = cell.rowspan;
        applyColumnStyles(td, c, grid.colsMeta);
        tr.appendChild(td);
      }
      tbody.appendChild(tr);
    }
    table.appendChild(tbody);
  }
  return table;
}
function applyColumnStyles(el, colIndex, colsMeta) {
  const meta = colsMeta[colIndex];
  if (!meta)
    return;
  if (meta.align === "left") {
    el.style.textAlign = "left";
  } else if (meta.align === "center") {
    el.style.textAlign = "center";
  } else if (meta.align === "right") {
    el.style.textAlign = "right";
  }
  if (meta.width) {
    el.style.width = meta.width;
  }
}

// src/live-preview.ts
var import_view = require("@codemirror/view");
var import_state = require("@codemirror/state");
var TableWidget = class extends import_view.WidgetType {
  // 不再需要 startPos
  constructor(markdown, plugin) {
    super();
    this.markdown = markdown;
    this.plugin = plugin;
  }
  eq(other) {
    return this.markdown === other.markdown;
  }
  toDOM(view) {
    const wrapper = document.createElement("div");
    wrapper.className = "md-xtable-preview-wrapper";
    const grid = parseMarkdownTable(this.markdown);
    if (!grid) {
      const errorEl = document.createElement("div");
      errorEl.className = "md-xtable-error";
      errorEl.textContent = "Error parsing table";
      return errorEl;
    }
    const contextVars = this.plugin.getVariablesContext();
    evaluateGrid(grid, contextVars);
    const tableEl = renderTable(grid);
    if (grid.tableMeta.attributes.height) {
      wrapper.style.maxHeight = grid.tableMeta.attributes.height;
      wrapper.style.overflowY = "auto";
    }
    if (grid.tableMeta.className) {
      wrapper.className += " " + grid.tableMeta.className;
    }
    wrapper.appendChild(tableEl);
    return wrapper;
  }
};
function tableLivePreviewField(plugin) {
  return import_state.StateField.define({
    create(state) {
      return buildTableDecorations(state, plugin);
    },
    update(decorations, tr) {
      if (tr.docChanged) {
        return buildTableDecorations(tr.state, plugin);
      }
      return decorations.map(tr.changes);
    },
    provide: (f) => import_view.EditorView.decorations.from(f)
  });
}
function buildTableDecorations(state, plugin) {
  const builder = [];
  const doc = state.doc;
  const blocks = findTableBlocks(doc);
  for (const block of blocks) {
    const widgetDeco = import_view.Decoration.widget({
      widget: new TableWidget(block.text, plugin),
      block: true,
      // 声明这是一个占据一整行的块级元素
      side: 1
      // side: 1 表示放在挂载点的下方
    });
    builder.push(widgetDeco.range(block.end));
  }
  builder.sort((a, b) => a.from - b.from);
  try {
    return import_view.Decoration.set(builder);
  } catch (error) {
    console.error("MD-XTable Debug -> DecorationSet \u6784\u5EFA\u5931\u8D25:", error);
    return import_view.Decoration.none;
  }
}
function findTableBlocks(doc) {
  const blocks = [];
  const linesCount = doc.lines;
  let inTable = false;
  let tableLines = [];
  let tableStartPos = -1;
  let tableEndPos = -1;
  for (let i = 1; i <= linesCount; i++) {
    const line = doc.line(i);
    const text = line.text;
    const isTableLine = text.trim().startsWith("|") || text.includes("|");
    if (isTableLine) {
      if (!inTable) {
        inTable = true;
        tableLines = [text];
        tableStartPos = line.from;
      } else {
        tableLines.push(text);
      }
      tableEndPos = line.to;
    } else {
      if (inTable) {
        if (text.trim().startsWith("<!--") && text.includes(".md-xtable")) {
          tableLines.push(text);
          tableEndPos = line.to;
          const tableText = tableLines.join("\n");
          if (isValidTable(tableText)) {
            blocks.push({ start: tableStartPos, end: tableEndPos, text: tableText });
          }
          inTable = false;
          tableLines = [];
        } else {
          const tableText = tableLines.join("\n");
          if (isValidTable(tableText)) {
            blocks.push({ start: tableStartPos, end: tableEndPos, text: tableText });
          }
          inTable = false;
          tableLines = [];
        }
      }
    }
  }
  if (inTable && tableLines.length > 0) {
    const tableText = tableLines.join("\n");
    if (isValidTable(tableText)) {
      blocks.push({ start: tableStartPos, end: tableEndPos, text: tableText });
    }
  }
  return blocks;
}
function isMDXTable(tableText) {
  if (tableText.includes(".md-xtable")) {
    return true;
  }
  if (tableText.includes(":=")) {
    return true;
  }
  const lines = tableText.split("\n");
  for (const line of lines) {
    const cells = line.split("|").map((c) => c.trim());
    if (cells.some((c) => c === "<" || c === "^^")) {
      return true;
    }
  }
  return false;
}
function isValidTable(tableText) {
  try {
    if (!isMDXTable(tableText)) {
      return false;
    }
    return parseMarkdownTable(tableText) !== null;
  } catch (e) {
    return false;
  }
}

// src/main.ts
var MDXTablePlugin = class extends import_obsidian.Plugin {
  async onload() {
    console.log("Loading MD-XTable Plugin...");
    this.registerMarkdownPostProcessor((el, ctx) => {
      this.processTable(el, ctx);
    });
    this.registerEditorExtension(import_state2.Prec.highest(tableLivePreviewField(this)));
  }
  onunload() {
    console.log("Unloading MD-XTable Plugin...");
  }
  processTable(el, ctx) {
    const nativeTable = el.querySelector("table");
    if (!nativeTable) {
      return;
    }
    const sectionInfo = ctx.getSectionInfo(el);
    if (!sectionInfo)
      return;
    const lines = sectionInfo.text.split("\n");
    const tableLines = lines.slice(sectionInfo.lineStart, sectionInfo.lineEnd + 1);
    const tableMarkdown = tableLines.join("\n");
    const grid = parseMarkdownTable(tableMarkdown);
    if (!grid)
      return;
    const contextVars = this.getVariablesContext();
    evaluateGrid(grid, contextVars);
    const newTable = renderTable(grid);
    let replacementNode = newTable;
    const hasHeight = !!grid.tableMeta.attributes.height;
    const hasAlignment = grid.tableMeta.className && (grid.tableMeta.className.includes("align-center") || grid.tableMeta.className.includes("align-right"));
    if (hasHeight || hasAlignment) {
      const wrapper = document.createElement("div");
      wrapper.className = "md-xtable-scroll-wrapper";
      if (grid.tableMeta.className) {
        wrapper.className += " " + grid.tableMeta.className;
      }
      if (hasHeight) {
        wrapper.style.maxHeight = grid.tableMeta.attributes.height;
        wrapper.style.overflowY = "auto";
      }
      wrapper.appendChild(newTable);
      replacementNode = wrapper;
    }
    nativeTable.replaceWith(replacementNode);
  }
  /**
   * Resolves numeric frontmatter variables and Dataview inline fields for the active file.
   */
  getVariablesContext() {
    const contextVars = {};
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile)
      return contextVars;
    let frontmatter = {};
    const cache = this.app.metadataCache.getFileCache(activeFile);
    if (cache && cache.frontmatter) {
      frontmatter = { ...cache.frontmatter };
    }
    const dv = this.app.plugins?.plugins?.dataview?.api;
    if (dv) {
      try {
        const page = dv.page(activeFile.path);
        if (page) {
          frontmatter = { ...frontmatter, ...page };
        }
      } catch (e) {
      }
    }
    for (const [key, val] of Object.entries(frontmatter)) {
      if (typeof val === "number") {
        contextVars[key] = val;
      } else if (typeof val === "string") {
        const cleaned = val.replace(/,/g, "").replace(/[^\d.-]/g, "").trim();
        const num = parseFloat(cleaned);
        if (!isNaN(num)) {
          contextVars[key] = num;
        }
      }
    }
    return contextVars;
  }
};
